### ISSUE TITLE
support fuse in FutureExt

### ISSUE THREAD

**Issue by GlenDC** [smol-rs/futures-lite#100]
Recently I switched from futures and futures-util to futures-lite. For the most case this was okay.

The only thing I did miss was the fuse functionality.

I implemented it here <https://github.com/plabayo/rama/blob/main/src/future.rs>.
Could I implement it in the actual futures-lite codebase.
Or what do you suggest?

**Comment by GlenDC** [comment]
If accepted I am willing to make a PR FWIW.

**Comment by GlenDC** [comment]
@notgull is there any interest for this?

**Comment by notgull** [comment]
Sorry, this fell through the cracks. Yes, I think this could be added, since it can't be trivially emulated with `async` blocks.
