### ISSUE TITLE
Where is the abstractions about `futures_sink` like `futures_util::SinkExt`?

### ISSUE THREAD

**Issue by stackinspector** [smol-rs/futures-lite#111]

**Comment by notgull** [comment]
`Sink` was a mistake, so it's not included in this repo.

**Comment by stackinspector** [comment]
Yet another mistake. Removing legacy is definitely a good thing, but where is the alternative? How can I use `async_tungstenite::WebSocketStream` to send messages? If API need to redesign, then where is the more correct interface that can do similar thing?

**Comment by stackinspector** [comment]
Generally I hope that there will be a compatibility/adapting/legacy list, listing all of the APIs in `futures` series crate (maybe also all of Tokio API for the entire Smol project), explaining if there is a drop-in alternative, or an alternative with what differences, or this is a legacy API with trap or footgun and use another API or way to implement it, or the alternative API has not yet been implemented. Or people will get frustrated trying to transfer previous practices to the new system, preventing it from further evolving.

**Comment by notgull** [comment]
I agree with the idea of such a list.

**Comment by notgull** [comment]
Closing this as "not planned" now that it's official policy to not support Sink.
