### ISSUE TITLE
Missing StreamExt::for_each_concurrent

### ISSUE THREAD

**Issue by andrewbanchich** [smol-rs/futures-lite#26]
I'm moving from `futures` to `futures-lite` but noticed this is missing [`StreamExt::for_each_concurrent`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.14/futures/stream/trait.StreamExt.html#method.for_each_concurrent).

**Comment by Iggdraisil** [comment]
Any progress on this?

**Comment by notgull** [comment]
You can effectively recreate the `for_each_concurrent` combinator by spawning each future into an executor, collecting those task handles into a list and then polling those task handles. This is the recommended solution, especially since the `futures` implementation has footguns in it.
