### ISSUE TITLE
parking vs std::thread::park

### ISSUE THREAD

**Issue by james7132** [smol-rs/futures-lite#53]
Is the `parking` crate strictly necessary when the standard library is available? According to the docs, `std::thread::park` has been available since 1.0 and looking at it's implementation, it seems very similar in the generic case to `parking`'s. It does seem to have per-platform optimizations too. An equivalent `Unparker` can be made wrapping a `std::thread::Thread` using `Thread::unpark`.

**Comment by taiki-e** [comment]
Closing per https://github.com/smol-rs/futures-lite/pull/54#issuecomment-1183361388.
