### ISSUE TITLE
map_ok from TryStreamExt and buffered from StreamExt

### ISSUE THREAD

**Issue by v1gnesh** [smol-rs/futures-lite#80]
Hello,

Would it be possible to add the following 2 to futures-lite?

https://docs.rs/futures-util/latest/futures_util/stream/trait.TryStreamExt.html#method.map_ok
https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.buffered

I'm trying to see if I can switch from futures-util and tokio to futures-lite and smol..

**EDIT:** I have to say though, futures-lite is taking 10-20x longer... maybe because I can't use `buffered()` here.

**Comment by notgull** [comment]
- For `map_ok`, usually we only add combinators like this when there are equivalent ones in `std`'s `Iterator`. This one can be implemented as a `match` statement in the `map` combinator, so I would be against adding it to avoid bloat.
- `futures-lite` intentionally avoids having combinators that require an executor to work. `buffered()` works by using an internal executor. So I don't think we should add it.

**Comment by v1gnesh** [comment]
@notgull, thanks for the detailed blog post. Have to say, the comments in the code block are almost invisible when trying to read with "night sight" on.
