### ISSUE TITLE
`or` but for different output types

### ISSUE THREAD

**Issue by Einliterflasche** [smol-rs/futures-lite#98]
Hey,

first of all, great work! I don't think the smol project get's enough recognition for its amazing work.

I learned from #65 that you have an `or` function which is like `select!` except in that it requires both futures to have the same output type. Is there already a function like `or` which works for two futures with distinct output types and returns an `Either` enum? 

If there is no such function as of yet I would like to try my hands at implementing it. I have thought of two issues:

1. what to name the function
2. this necessitates an `Either` struct we would either (ba dum tsss) need to implement ourselves or depend on an an (albeit small) [`either` crate](https://lib.rs/crates/either).

I think this would be a very useful and straight forward addition.

**Comment by notgull** [comment]
I think you can just use the `either` crate in combination with `or` to do this. For example:

```rust
let a = async { /* ... */ };
let b = async { /* ... */ };

let combo = async move { Either::Left(a.await) }.or(async move { Either::Right(b.await) });
match combo.await {
    Either::Left(a) => /* ... */,
    Either::Right(b) => /* ... */
}
```

**Comment by Einliterflasche** [comment]
True! thanks for the quick reply
